import = ['C:\Users\Aaron\AppData\Roaming\alacritty\themes\oceanic_next.toml']

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[shell]
args = ["-d Ubuntu-22.04"]
program = 'C:\Windows\System32\wsl.exe ~'

[window]
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 2
y = 1
