[general]
import = ['C:\Users\Aaron\AppData\Roaming\alacritty\themes\oceanic_next.toml']

[env]
# TERM = "xterm-256color"

[window]
padding = { x = 2, y = 2 }
dynamic_padding = true
startup_mode = "Maximized"
dynamic_title = true

[font]
size = 11.25
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[terminal]
shell = { program = 'C:\Windows\System32\wsl.exe ~', args = ["-d Ubuntu-22.04"] }
