#! /usr/bin/bash 

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd) 

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Tmux
# ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
ln -sf $DOTFILES/tmux/tmux.conf.local $HOME/.config/tmux/tmux.conf.local
ln -sf $DOTFILES/tmux/session.sh $HOME/.local/bin/tmux-session

# zsh
ln -sf $DOTFILES/zsh/aliases.zsh $HOME/.oh-my-zsh/custom/aliases.zsh
ln -sf $DOTFILES/zsh/env.zsh $HOME/.oh-my-zsh/custom/env.zsh
