#! /usr/bin/bash 

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd) 

# rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim-laracasts

ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf
